version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/satellitedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      NASA_API_USERNAME: ${NASA_API_USERNAME}
      NASA_API_PASSWORD: ${NASA_API_PASSWORD}
      NASA_API_URL: https://www.space-track.org
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: satellitedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"