spring.application.name=Satellite Collision Detection

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/satellitedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

nasa.api.username=${NASA_API_USERNAME:}
nasa.api.password=${NASA_API_PASSWORD:}
nasa.api.url=${NASA_API_URL:https://www.space-track.org}

server.port=${PORT:8080}